function create_data() {
  var DATA_LENGTH = 8000;
  var data = [];
  for (var i = 0; i < DATA_LENGTH; i++)
    data.push((i % 26) + 65);
  return data;
}


function create_text_old() {
  var mystring = "hello bob!" + "\n";
  var addit = "how are you??" + "\n";
  mystring = mystring+mystring+addit+mystring+addit+addit+mystring+mystring+mystring+addit+mystring+mystring+mystring+mystring + "\0";
  var data = [];
  for (var i = 0; i < mystring.length; i++)
    data.push(mystring.charCodeAt(i));
  return data;
}


function create_text() {
  var str =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo tincidunt erat vel posuere. Duis id lacus sed nulla finibus scelerisque at et turpis. Suspendisse efficitur vel nisi non eleifend. Sed vel faucibus turpis. Duis tincidunt at risus nec auctor. Maecenas nec sodales velit. Quisque justo massa, fringilla nec rhoncus sed, mattis et sapien. Sed diam nunc, viverra vitae scelerisque sit amet, volutpat eget ligula. Fusce nec bibendum est. Ut ultricies tellus dui, nec dapibus velit mattis sed. Pellentesque id posuere leo, sit amet fringilla massa. Nulla est eros, congue eu blandit at, hendrerit sed velit. Sed neque nunc, mollis et vestibulum a, ultrices in arcu." +
      "Aenean et suscipit ante, condimentum dictum lectus. Nam magna tortor, elementum eget orci vitae, pellentesque consectetur dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla et magna luctus, maximus augue a, facilisis purus. Aenean at iaculis ante, id convallis erat. Etiam sed tincidunt nulla. Duis viverra molestie dapibus. Suspendisse eu metus non nulla finibus aliquet. Integer at sapien eu nunc mollis facilisis. Quisque ut tellus dolor. Sed volutpat sed arcu vel commodo. Proin eleifend nisi a ultrices porttitor. Proin eu diam vitae magna posuere feugiat. Cras ut mattis odio, fringilla tempor dui."+
      "Morbi massa purus, vulputate vel condimentum sed, tempor vitae arcu. Proin egestas mattis eros quis pharetra. Vivamus eu vehicula massa. Sed aliquet mi nulla, a gravida leo luctus sed. Nulla tincidunt nec lacus eu ultrices. Vestibulum mollis tristique ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat porta lorem, vitae sollicitudin quam vulputate ac."+
      "Integer vitae porta leo. Nullam bibendum varius consectetur. Mauris consequat nulla eu varius vestibulum. Donec a orci tempus, gravida orci a, tincidunt dolor. Cras dapibus porta nibh id ultrices. Donec eget est quis risus feugiat consectetur id nec urna. Ut maximus fringilla nisi, et interdum sapien rutrum eu. In hac habitasse platea dictumst. Sed egestas posuere turpis, quis luctus sapien aliquam a. Quisque nec tempor enim. Curabitur volutpat ultricies nisl, in posuere ligula convallis ut. In semper mauris nulla, et dapibus erat tristique at. Suspendisse eget neque quis elit commodo dapibus. Quisque pharetra lorem id ante volutpat bibendum dignissim eget nunc. Suspendisse interdum tortor massa, a blandit turpis sollicitudin vel."+
      "Donec non dictum odio. Morbi eu odio eu dui tempor ullamcorper. Praesent sollicitudin venenatis justo, vitae bibendum tellus pulvinar ultricies. Vivamus at urna fringilla, tempus metus at, finibus purus. Cras et eros vitae lacus consectetur pretium. In venenatis luctus orci vel sodales. Vestibulum mollis lobortis lorem et scelerisque. Aenean sagittis purus sed turpis sollicitudin, at pharetra sapien tempor. Fusce eget maximus tellus. Aliquam bibendum nisl ut enim malesuada, eu blandit justo luctus. Curabitur cursus lectus id nisi lacinia, ac semper magna eleifend. Donec interdum tincidunt ligula, nec viverra turpis. Praesent non volutpat est. Mauris ut commodo leo. Maecenas justo nisl, volutpat at est eu, rutrum vulputate nulla." +

      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo tincidunt erat vel posuere. Duis id lacus sed nulla finibus scelerisque at et turpis. Suspendisse efficitur vel nisi non eleifend. Sed vel faucibus turpis. Duis tincidunt at risus nec auctor. Maecenas nec sodales velit. Quisque justo massa, fringilla nec rhoncus sed, mattis et sapien. Sed diam nunc, viverra vitae scelerisque sit amet, volutpat eget ligula. Fusce nec bibendum est. Ut ultricies tellus dui, nec dapibus velit mattis sed. Pellentesque id posuere leo, sit amet fringilla massa. Nulla est eros, congue eu blandit at, hendrerit sed velit. Sed neque nunc, mollis et vestibulum a, ultrices in arcu." +
      "Aenean et suscipit ante, condimentum dictum lectus. Nam magna tortor, elementum eget orci vitae, pellentesque consectetur dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla et magna luctus, maximus augue a, facilisis purus. Aenean at iaculis ante, id convallis erat. Etiam sed tincidunt nulla. Duis viverra molestie dapibus. Suspendisse eu metus non nulla finibus aliquet. Integer at sapien eu nunc mollis facilisis. Quisque ut tellus dolor. Sed volutpat sed arcu vel commodo. Proin eleifend nisi a ultrices porttitor. Proin eu diam vitae magna posuere feugiat. Cras ut mattis odio, fringilla tempor dui."+
      "Morbi massa purus, vulputate vel condimentum sed, tempor vitae arcu. Proin egestas mattis eros quis pharetra. Vivamus eu vehicula massa. Sed aliquet mi nulla, a gravida leo luctus sed. Nulla tincidunt nec lacus eu ultrices. Vestibulum mollis tristique ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat porta lorem, vitae sollicitudin quam vulputate ac."+
      "Integer vitae porta leo. Nullam bibendum varius consectetur. Mauris consequat nulla eu varius vestibulum. Donec a orci tempus, gravida orci a, tincidunt dolor. Cras dapibus porta nibh id ultrices. Donec eget est quis risus feugiat consectetur id nec urna. Ut maximus fringilla nisi, et interdum sapien rutrum eu. In hac habitasse platea dictumst. Sed egestas posuere turpis, quis luctus sapien aliquam a. Quisque nec tempor enim. Curabitur volutpat ultricies nisl, in posuere ligula convallis ut. In semper mauris nulla, et dapibus erat tristique at. Suspendisse eget neque quis elit commodo dapibus. Quisque pharetra lorem id ante volutpat bibendum dignissim eget nunc. Suspendisse interdum tortor massa, a blandit turpis sollicitudin vel."+
      "Donec non dictum odio. Morbi eu odio eu dui tempor ullamcorper. Praesent sollicitudin venenatis justo, vitae bibendum tellus pulvinar ultricies. Vivamus at urna fringilla, tempus metus at, finibus purus. Cras et eros vitae lacus consectetur pretium. In venenatis luctus orci vel sodales. Vestibulum mollis lobortis lorem et scelerisque. Aenean sagittis purus sed turpis sollicitudin, at pharetra sapien tempor. Fusce eget maximus tellus. Aliquam bibendum nisl ut enim malesuada, eu blandit justo luctus. Curabitur cursus lectus id nisi lacinia, ac semper magna eleifend. Donec interdum tincidunt ligula, nec viverra turpis. Praesent non volutpat est. Mauris ut commodo leo. Maecenas justo nisl, volutpat at est eu, rutrum vulputate nulla." +

      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo tincidunt erat vel posuere. Duis id lacus sed nulla finibus scelerisque at et turpis. Suspendisse efficitur vel nisi non eleifend. Sed vel faucibus turpis. Duis tincidunt at risus nec auctor. Maecenas nec sodales velit. Quisque justo massa, fringilla nec rhoncus sed, mattis et sapien. Sed diam nunc, viverra vitae scelerisque sit amet, volutpat eget ligula. Fusce nec bibendum est. Ut ultricies tellus dui, nec dapibus velit mattis sed. Pellentesque id posuere leo, sit amet fringilla massa. Nulla est eros, congue eu blandit at, hendrerit sed velit. Sed neque nunc, mollis et vestibulum a, ultrices in arcu." +
      "Aenean et suscipit ante, condimentum dictum lectus. Nam magna tortor, elementum eget orci vitae, pellentesque consectetur dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla et magna luctus, maximus augue a, facilisis purus. Aenean at iaculis ante, id convallis erat. Etiam sed tincidunt nulla. Duis viverra molestie dapibus. Suspendisse eu metus non nulla finibus aliquet. Integer at sapien eu nunc mollis facilisis. Quisque ut tellus dolor. Sed volutpat sed arcu vel commodo. Proin eleifend nisi a ultrices porttitor. Proin eu diam vitae magna posuere feugiat. Cras ut mattis odio, fringilla tempor dui."+
      "Morbi massa purus, vulputate vel condimentum sed, tempor vitae arcu. Proin egestas mattis eros quis pharetra. Vivamus eu vehicula massa. Sed aliquet mi nulla, a gravida leo luctus sed. Nulla tincidunt nec lacus eu ultrices. Vestibulum mollis tristique ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat porta lorem, vitae sollicitudin quam vulputate ac."+
      "Integer vitae porta leo. Nullam bibendum varius consectetur. Mauris consequat nulla eu varius vestibulum. Donec a orci tempus, gravida orci a, tincidunt dolor. Cras dapibus porta nibh id ultrices. Donec eget est quis risus feugiat consectetur id nec urna. Ut maximus fringilla nisi, et interdum sapien rutrum eu. In hac habitasse platea dictumst. Sed egestas posuere turpis, quis luctus sapien aliquam a. Quisque nec tempor enim. Curabitur volutpat ultricies nisl, in posuere ligula convallis ut. In semper mauris nulla, et dapibus erat tristique at. Suspendisse eget neque quis elit commodo dapibus. Quisque pharetra lorem id ante volutpat bibendum dignissim eget nunc. Suspendisse interdum tortor massa, a blandit turpis sollicitudin vel."+
      "Donec non dictum odio. Morbi eu odio eu dui tempor ullamcorper. Praesent sollicitudin venenatis justo, vitae bibendum tellus pulvinar ultricies. Vivamus at urna fringilla, tempus metus at, finibus purus. Cras et eros vitae lacus consectetur pretium. In venenatis luctus orci vel sodales. Vestibulum mollis lobortis lorem et scelerisque. Aenean sagittis purus sed turpis sollicitudin, at pharetra sapien tempor. Fusce eget maximus tellus. Aliquam bibendum nisl ut enim malesuada, eu blandit justo luctus. Curabitur cursus lectus id nisi lacinia, ac semper magna eleifend. Donec interdum tincidunt ligula, nec viverra turpis. Praesent non volutpat est. Mauris ut commodo leo. Maecenas justo nisl, volutpat at est eu, rutrum vulputate nulla." +

      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo tincidunt erat vel posuere. Duis id lacus sed nulla finibus scelerisque at et turpis. Suspendisse efficitur vel nisi non eleifend. Sed vel faucibus turpis. Duis tincidunt at risus nec auctor. Maecenas nec sodales velit. Quisque justo massa, fringilla nec rhoncus sed, mattis et sapien. Sed diam nunc, viverra vitae scelerisque sit amet, volutpat eget ligula. Fusce nec bibendum est. Ut ultricies tellus dui, nec dapibus velit mattis sed. Pellentesque id posuere leo, sit amet fringilla massa. Nulla est eros, congue eu blandit at, hendrerit sed velit. Sed neque nunc, mollis et vestibulum a, ultrices in arcu." +
      "Aenean et suscipit ante, condimentum dictum lectus. Nam magna tortor, elementum eget orci vitae, pellentesque consectetur dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla et magna luctus, maximus augue a, facilisis purus. Aenean at iaculis ante, id convallis erat. Etiam sed tincidunt nulla. Duis viverra molestie dapibus. Suspendisse eu metus non nulla finibus aliquet. Integer at sapien eu nunc mollis facilisis. Quisque ut tellus dolor. Sed volutpat sed arcu vel commodo. Proin eleifend nisi a ultrices porttitor. Proin eu diam vitae magna posuere feugiat. Cras ut mattis odio, fringilla tempor dui."+
      "Morbi massa purus, vulputate vel condimentum sed, tempor vitae arcu. Proin egestas mattis eros quis pharetra. Vivamus eu vehicula massa. Sed aliquet mi nulla, a gravida leo luctus sed. Nulla tincidunt nec lacus eu ultrices. Vestibulum mollis tristique ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat porta lorem, vitae sollicitudin quam vulputate ac."+
      "Integer vitae porta leo. Nullam bibendum varius consectetur. Mauris consequat nulla eu varius vestibulum. Donec a orci tempus, gravida orci a, tincidunt dolor. Cras dapibus porta nibh id ultrices. Donec eget est quis risus feugiat consectetur id nec urna. Ut maximus fringilla nisi, et interdum sapien rutrum eu. In hac habitasse platea dictumst. Sed egestas posuere turpis, quis luctus sapien aliquam a. Quisque nec tempor enim. Curabitur volutpat ultricies nisl, in posuere ligula convallis ut. In semper mauris nulla, et dapibus erat tristique at. Suspendisse eget neque quis elit commodo dapibus. Quisque pharetra lorem id ante volutpat bibendum dignissim eget nunc. Suspendisse interdum tortor massa, a blandit turpis sollicitudin vel."+
      "Donec non dictum odio. Morbi eu odio eu dui tempor ullamcorper. Praesent sollicitudin venenatis justo, vitae bibendum tellus pulvinar ultricies. Vivamus at urna fringilla, tempus metus at, finibus purus. Cras et eros vitae lacus consectetur pretium. In venenatis luctus orci vel sodales. Vestibulum mollis lobortis lorem et scelerisque. Aenean sagittis purus sed turpis sollicitudin, at pharetra sapien tempor. Fusce eget maximus tellus. Aliquam bibendum nisl ut enim malesuada, eu blandit justo luctus. Curabitur cursus lectus id nisi lacinia, ac semper magna eleifend. Donec interdum tincidunt ligula, nec viverra turpis. Praesent non volutpat est. Mauris ut commodo leo. Maecenas justo nisl, volutpat at est eu, rutrum vulputate nulla." +

      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo tincidunt erat vel posuere. Duis id lacus sed nulla finibus scelerisque at et turpis. Suspendisse efficitur vel nisi non eleifend. Sed vel faucibus turpis. Duis tincidunt at risus nec auctor. Maecenas nec sodales velit. Quisque justo massa, fringilla nec rhoncus sed, mattis et sapien. Sed diam nunc, viverra vitae scelerisque sit amet, volutpat eget ligula. Fusce nec bibendum est. Ut ultricies tellus dui, nec dapibus velit mattis sed. Pellentesque id posuere leo, sit amet fringilla massa. Nulla est eros, congue eu blandit at, hendrerit sed velit. Sed neque nunc, mollis et vestibulum a, ultrices in arcu." +
      "Aenean et suscipit ante, condimentum dictum lectus. Nam magna tortor, elementum eget orci vitae, pellentesque consectetur dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla et magna luctus, maximus augue a, facilisis purus. Aenean at iaculis ante, id convallis erat. Etiam sed tincidunt nulla. Duis viverra molestie dapibus. Suspendisse eu metus non nulla finibus aliquet. Integer at sapien eu nunc mollis facilisis. Quisque ut tellus dolor. Sed volutpat sed arcu vel commodo. Proin eleifend nisi a ultrices porttitor. Proin eu diam vitae magna posuere feugiat. Cras ut mattis odio, fringilla tempor dui."+
      "Morbi massa purus, vulputate vel condimentum sed, tempor vitae arcu. Proin egestas mattis eros quis pharetra. Vivamus eu vehicula massa. Sed aliquet mi nulla, a gravida leo luctus sed. Nulla tincidunt nec lacus eu ultrices. Vestibulum mollis tristique ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat porta lorem, vitae sollicitudin quam vulputate ac."+
      "Integer vitae porta leo. Nullam bibendum varius consectetur. Mauris consequat nulla eu varius vestibulum. Donec a orci tempus, gravida orci a, tincidunt dolor. Cras dapibus porta nibh id ultrices. Donec eget est quis risus feugiat consectetur id nec urna. Ut maximus fringilla nisi, et interdum sapien rutrum eu. In hac habitasse platea dictumst. Sed egestas posuere turpis, quis luctus sapien aliquam a. Quisque nec tempor enim. Curabitur volutpat ultricies nisl, in posuere ligula convallis ut. In semper mauris nulla, et dapibus erat tristique at. Suspendisse eget neque quis elit commodo dapibus. Quisque pharetra lorem id ante volutpat bibendum dignissim eget nunc. Suspendisse interdum tortor massa, a blandit turpis sollicitudin vel."+
      "Donec non dictum odio. Morbi eu odio eu dui tempor ullamcorper. Praesent sollicitudin venenatis justo, vitae bibendum tellus pulvinar ultricies. Vivamus at urna fringilla, tempus metus at, finibus purus. Cras et eros vitae lacus consectetur pretium. In venenatis luctus orci vel sodales. Vestibulum mollis lobortis lorem et scelerisque. Aenean sagittis purus sed turpis sollicitudin, at pharetra sapien tempor. Fusce eget maximus tellus. Aliquam bibendum nisl ut enim malesuada, eu blandit justo luctus. Curabitur cursus lectus id nisi lacinia, ac semper magna eleifend. Donec interdum tincidunt ligula, nec viverra turpis. Praesent non volutpat est. Mauris ut commodo leo. Maecenas justo nisl, volutpat at est eu, rutrum vulputate nulla." +

      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo tincidunt erat vel posuere. Duis id lacus sed nulla finibus scelerisque at et turpis. Suspendisse efficitur vel nisi non eleifend. Sed vel faucibus turpis. Duis tincidunt at risus nec auctor. Maecenas nec sodales velit. Quisque justo massa, fringilla nec rhoncus sed, mattis et sapien. Sed diam nunc, viverra vitae scelerisque sit amet, volutpat eget ligula. Fusce nec bibendum est. Ut ultricies tellus dui, nec dapibus velit mattis sed. Pellentesque id posuere leo, sit amet fringilla massa. Nulla est eros, congue eu blandit at, hendrerit sed velit. Sed neque nunc, mollis et vestibulum a, ultrices in arcu." +
      "Aenean et suscipit ante, condimentum dictum lectus. Nam magna tortor, elementum eget orci vitae, pellentesque consectetur dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla et magna luctus, maximus augue a, facilisis purus. Aenean at iaculis ante, id convallis erat. Etiam sed tincidunt nulla. Duis viverra molestie dapibus. Suspendisse eu metus non nulla finibus aliquet. Integer at sapien eu nunc mollis facilisis. Quisque ut tellus dolor. Sed volutpat sed arcu vel commodo. Proin eleifend nisi a ultrices porttitor. Proin eu diam vitae magna posuere feugiat. Cras ut mattis odio, fringilla tempor dui."+
      "Morbi massa purus, vulputate vel condimentum sed, tempor vitae arcu. Proin egestas mattis eros quis pharetra. Vivamus eu vehicula massa. Sed aliquet mi nulla, a gravida leo luctus sed. Nulla tincidunt nec lacus eu ultrices. Vestibulum mollis tristique ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat porta lorem, vitae sollicitudin quam vulputate ac."+
      "Integer vitae porta leo. Nullam bibendum varius consectetur. Mauris consequat nulla eu varius vestibulum. Donec a orci tempus, gravida orci a, tincidunt dolor. Cras dapibus porta nibh id ultrices. Donec eget est quis risus feugiat consectetur id nec urna. Ut maximus fringilla nisi, et interdum sapien rutrum eu. In hac habitasse platea dictumst. Sed egestas posuere turpis, quis luctus sapien aliquam a. Quisque nec tempor enim. Curabitur volutpat ultricies nisl, in posuere ligula convallis ut. In semper mauris nulla, et dapibus erat tristique at. Suspendisse eget neque quis elit commodo dapibus. Quisque pharetra lorem id ante volutpat bibendum dignissim eget nunc. Suspendisse interdum tortor massa, a blandit turpis sollicitudin vel."+
      "Donec non dictum odio. Morbi eu odio eu dui tempor ullamcorper. Praesent sollicitudin venenatis justo, vitae bibendum tellus pulvinar ultricies. Vivamus at urna fringilla, tempus metus at, finibus purus. Cras et eros vitae lacus consectetur pretium. In venenatis luctus orci vel sodales. Vestibulum mollis lobortis lorem et scelerisque. Aenean sagittis purus sed turpis sollicitudin, at pharetra sapien tempor. Fusce eget maximus tellus. Aliquam bibendum nisl ut enim malesuada, eu blandit justo luctus. Curabitur cursus lectus id nisi lacinia, ac semper magna eleifend. Donec interdum tincidunt ligula, nec viverra turpis. Praesent non volutpat est. Mauris ut commodo leo. Maecenas justo nisl, volutpat at est eu, rutrum vulputate nulla." +

      "";

  var data = [];
  for (var i = 0; i < str.length; i++)
    data.push(str.charCodeAt(i));
  return data;
}

//exports.create_data = create_data;
exports.create_data = create_text;
